services:
  nextjs: 
      container_name: nextjs-app
      build: 
        context: .
        dockerfile: Dockerfile
      ports: 
        - "3000:3000" 
      env_file: 
        - .env
      environment: 
        DATABASE_URL: ${DB_URI}
      volumes: 
        - ./src:/app/src  # Only syncs src directory
        - ./public:/app/public  # Only syncs public directory 
      restart: unless-stopped
      command: npm run dev
 